Extra exception handling to catch interrupted errors
Scarsz/JDAAppender pull request #26
Opened 2024-07-28 10:36 UTC by Dinty1

2024-07-29 07:57 UTC, Vankka requested changes
Has to be duplicated for `editMessage`, this also does not compile

2024-07-29 07:57 UTC, Vankka commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +                if (ex instanceof InterruptedIOException || ex.getCause() instanceof InterruptedException) return;
```suggestion
                if (ex instanceof InterruptedIOException || ex instanceof InterruptedException) return;
```

2024-07-29 07:57 UTC, Vankka commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +                if (e instanceof InterruptedException) {
This isn't needed anymore

2024-07-30 12:35 UTC, Dinty1 commented
Still doesn't compile on my end but that might be because my dev environment is messed up.

2024-07-30 15:54 UTC, Vankka requested changes
See in-line comments.

The exception handling matches on both these places that could be extracted to a method but not required

JDA5 module should also match these changes

2024-07-30 15:54 UTC, Vankka commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +            return currentMessage;
Please throw here as it did previously and only return when a interrupt is hit

2024-07-30 15:54 UTC, Vankka commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +                return currentMessage;
Please throw here as it did previously and only return when a interrupt is hit

2024-07-30 23:28 UTC, granny requested changes
some nitpicks

2024-07-30 23:28 UTC, granny commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
>  import java.io.PrintStream;
```suggestion
import java.io.Flushable;
import java.io.PrintStream;
```

2024-07-30 23:28 UTC, granny commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +            else throw new RuntimeException(e);
```suggestion
            throw new RuntimeException(e);
```

2024-07-30 23:28 UTC, granny commented on jda4/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java
> +                        && ((ErrorResponseException) e.getCause()).getErrorResponse() == ErrorResponse.UNKNOWN_MESSAGE) {
```suggestion
                if (this.isInterruptedException(e)) return currentMessage;
                Throwable cause = e.getCause();
                if (cause instanceof ErrorResponseException
                        && ((ErrorResponseException) cause).getErrorResponse() == ErrorResponse.UNKNOWN_MESSAGE) {
```

2024-07-31 04:41 UTC, Vankka approved these changes

2024-07-31 05:32 UTC, merged